### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by dangeratio** [dnet/swram-opengl#1]
Traceback (most recent call last):
  File "swram-opengl.py", line 182, in <module>
    init()
  File "swram-opengl.py", line 153, in init
    glMatrixMode(GL_MODELVIEW)
  File "errorchecker.pyx", line 53, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError (src/errorchecker.c:1218)
OpenGL.error.GLError: GLError(
    err = 1281,
    description = 'invalid value',
    baseOperation = glMatrixMode,
    cArguments = (GL_MODELVIEW,)
)

**Comment by dnet** [comment]
What version of PyOpenGL are you using? It works for me in 3.0.2-1, but [similar problems are reported](https://groups.google.com/forum/#!topic/pupil-discuss/x39qaYGF5Pw) in 3.1. If you have that, consider downgrading.

**Comment by dangeratio** [comment]
That was it, thanks!
